# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210216_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
