# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210217_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='year',
            field=models.IntegerField(max_length=3000),
        ),
    ]
